apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: loki
    release: loki
  ports:
    - name: http-metrics
      port: 3100
      targetPort: http-metrics
      protocol: TCP

