apiVersion: v1
kind: Secret
metadata:
  name: loki
  namespace: monitoring
type: Opaque
data:
  loki.yaml: |
    YXV0aF9lbmFibGVkOiBmYWxzZQpjaHVua19zdG9yZV9jb25maWc6CiAgbWF4X2xv...
    (생략)
    ...ZXRlbnRpb25fcGVyaW9kOiAwcw==

