apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  serviceName: loki-headless
  selector:
    matchLabels:
      app: loki
      release: loki
  template:
    metadata:
      labels:
        app: loki
        release: loki
    spec:
      serviceAccountName: loki
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        runAsNonRoot: true
      containers:
      - name: loki
        image: grafana/loki:2.6.1
        imagePullPolicy: IfNotPresent
        args:
        - -config.file=/etc/loki/loki.yaml
        ports:
        - containerPort: 3100
          name: http-metrics
        - containerPort: 9095
          name: grpc
        - containerPort: 7946
          name: memberlist-port
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: tmp
          mountPath: /tmp
        - name: storage
          mountPath: /data
      volumes:
      - name: config
        secret:
          secretName: loki
      - name: tmp
        emptyDir: {}
      - name: storage
        emptyDir: {}

