apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: falco
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: falco
      app.kubernetes.io/name: falco
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: falco
        app.kubernetes.io/name: falco
    spec:
      serviceAccountName: falco
      containers:
      - name: falco
        image: docker.io/falcosecurity/falco:0.42.1
        imagePullPolicy: IfNotPresent
        args:
        - /usr/bin/falco
        env:
        - name: HOST_ROOT
          value: /host
        - name: FALCO_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: FALCO_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: web
          containerPort: 8765
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8765
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8765
          initialDelaySeconds: 30
          periodSeconds: 15
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: container-engine-socket-0
          mountPath: /host/var/run/docker.sock
        - name: container-engine-socket-1
          mountPath: /host/run/podman/podman.sock
        - name: container-engine-socket-2
          mountPath: /host/run/host-containerd/containerd.sock
        - name: container-engine-socket-3
          mountPath: /host/run/containerd/containerd.sock
        - name: container-engine-socket-4
          mountPath: /host/run/crio/crio.sock
        - name: container-engine-socket-5
          mountPath: /host/run/k3s/containerd/containerd.sock
        - name: rulesfiles-install-dir
          mountPath: /etc/falco
        - name: plugins-install-dir
          mountPath: /usr/share/falco/plugins
        - name: specialized-falco-configs
          mountPath: /etc/falco/config.d
        - name: root-falco-fs
          mountPath: /root/.falco
        - name: proc-fs
          mountPath: /host/proc
        - name: etc-fs
          mountPath: /host/etc
          readOnly: true
        - name: dev-fs
          mountPath: /host/dev
          readOnly: true
        - name: sys-module-fs
          mountPath: /sys/module
        - name: sys-fs
          mountPath: /sys/kernel
          readOnly: true
        - name: falco-yaml
          mountPath: /etc/falco/falco.yaml
          subPath: falco.yaml

      - name: falcoctl-artifact-follow
        image: docker.io/falcosecurity/falcoctl:0.11.4
        args: ["artifact", "follow", "--log-format=json"]
        volumeMounts:
        - name: plugins-install-dir
          mountPath: /plugins
        - name: rulesfiles-install-dir
          mountPath: /rulesfiles
        - name: falcoctl-config-volume
          mountPath: /etc/falcoctl

      initContainers:
      - name: falco-driver-loader
        image: docker.io/falcosecurity/falco-driver-loader:0.42.1
        imagePullPolicy: IfNotPresent
        args: ["auto"]
        securityContext:
          privileged: true
        env:
        - name: HOST_ROOT
          value: /host
        - name: FALCOCTL_DRIVER_CONFIG_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: FALCOCTL_DRIVER_CONFIG_CONFIGMAP
          value: falco
        volumeMounts:
        - name: root-falco-fs
          mountPath: /root/.falco
        - name: proc-fs
          mountPath: /host/proc
          readOnly: true
        - name: boot-fs
          mountPath: /host/boot
          readOnly: true
        - name: lib-modules
          mountPath: /host/lib/modules
        - name: usr-fs
          mountPath: /host/usr
          readOnly: true
        - name: etc-fs
          mountPath: /host/etc
          readOnly: true
        - name: specialized-falco-configs
          mountPath: /etc/falco/config.d

      - name: falcoctl-artifact-install
        image: docker.io/falcosecurity/falcoctl:0.11.4
        args: ["artifact", "install", "--log-format=json"]
        volumeMounts:
        - name: plugins-install-dir
          mountPath: /plugins
        - name: rulesfiles-install-dir
          mountPath: /rulesfiles
        - name: falcoctl-config-volume
          mountPath: /etc/falcoctl

      securityContext: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: container-engine-socket-0
        hostPath:
          path: /var/run/docker.sock
      - name: container-engine-socket-1
        hostPath:
          path: /run/podman/podman.sock
      - name: container-engine-socket-2
        hostPath:
          path: /run/host-containerd/containerd.sock
      - name: container-engine-socket-3
        hostPath:
          path: /run/containerd/containerd.sock
      - name: container-engine-socket-4
        hostPath:
          path: /run/crio/crio.sock
      - name: container-engine-socket-5
        hostPath:
          path: /run/k3s/containerd/containerd.sock

      - name: specialized-falco-configs
        emptyDir: {}
      - name: plugins-install-dir
        emptyDir: {}
      - name: rulesfiles-install-dir
        emptyDir: {}
      - name: root-falco-fs
        emptyDir: {}
      - name: boot-fs
        hostPath:
          path: /boot
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-fs
        hostPath:
          path: /usr
      - name: etc-fs
        hostPath:
          path: /etc
      - name: dev-fs
        hostPath:
          path: /dev
      - name: sys-module-fs
        hostPath:
          path: /sys/module
      - name: sys-fs
        hostPath:
          path: /sys/kernel
      - name: proc-fs
        hostPath:
          path: /proc
      - name: falcoctl-config-volume
        configMap:
          name: falco-falcoctl
      - name: falco-yaml
        configMap:
          name: falco
          items:
          - key: falco.yaml
            path: falco.yaml

