apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcosidekick
  namespace: falco
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: core
      app.kubernetes.io/instance: falcosidekick
      app.kubernetes.io/name: falcosidekick
  template:
    metadata:
      labels:
        app.kubernetes.io/component: core
        app.kubernetes.io/instance: falcosidekick
        app.kubernetes.io/name: falcosidekick
    spec:
      serviceAccountName: falcosidekick
      containers:
      - name: falcosidekick
        image: docker.io/falcosecurity/falcosidekick:2.32.0
        imagePullPolicy: IfNotPresent
        env:
        - name: DEBUG
          value: "false"
        envFrom:
        - secretRef:
            name: falcosidekick
        ports:
        - containerPort: 2801
          name: http
        - containerPort: 2810
          name: http-notls
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources: {}
      securityContext:
        fsGroup: 1234
        runAsUser: 1234
      restartPolicy: Always

